stages:
  prepare:
    cmd: poetry run prepare -r data/iris.csv -p data/prepared
    deps:
    - data/iris.csv
    - iris_flower_classification/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: poetry run train --dataset-path data/prepared/train.csv --model-path model.pkl
    deps:
    - data/prepared/train.csv
    - iris_flower_classification/train.py
    outs:
    - model.pkl
  evaluate:
    cmd: poetry run evaluate --model-path model.pkl --dataset-path data/prepared/test.csv
    deps:
    - data/prepared/test.csv
    - iris_flower_classification/evaluate.py
    metrics:
    - dvclive/metrics.json
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
